[forest]
trees = ["trees", "localcharts/forest/trees", "bci/stages"]
assets = ["assets", "theme", "localcharts/forest/assets"]
theme = "theme"
root = "horse-0001"
base_url = "https://bci.horse"
host = "plurigrid"
