#!/usr/bin/env bash

VERSION=4.3.1

OS_NAME=$(uname)

if [[ "$OS_NAME" == "Darwin" ]]; then
  OS="macos"
elif [[ "$OS_NAME" == "Linux" ]]; then
  OS="linux"
else
  echo "Unsupported OS $OS_NAME"
  exit 1
fi

ARCH=$(uname -m)

SPEC="$VERSION-$OS-$ARCH"

TARFILE="forester-$SPEC.tar.gz"

FORESTER_URL="http://forester-builds.s3-website.us-east-2.amazonaws.com/$TARFILE"

FORESTER_DIR="$HOME/.forester/$VERSION"
FORESTER="$FORESTER_DIR/forester"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ ! -f "$FORESTER" ]]; then
  mkdir -p "$FORESTER_DIR"
  PREV=$(pwd)
  TMP=$(mktemp -d)
  cd $TMP
  curl -fSL -O $FORESTER_URL
  if [[ -f "$SCRIPT_DIR/checksums.txt" ]]; then
    cp "$SCRIPT_DIR/checksums.txt" $TMP
    if command -v sha256sum &>/dev/null; then
      sha256sum -c checksums.txt --ignore-missing
    elif command -v shasum &>/dev/null; then
      shasum -a 256 -c checksums.txt --ignore-missing
    fi
    if [[ $? -ne 0 ]]; then
      echo "invalid checksum"
      exit 1
    fi
  fi
  tar -xf $TARFILE
  mv forester "$FORESTER_DIR"
  cd $PREV
  rm -rf $TMP
fi

$FORESTER $@
